version: '2'

services:
  mail:
    # This is a SMTP docker container for sending emails. Can also relay emails to GMail and Amazon SES.
    # See: https://hub.docker.com/r/namshi/smtp
    container_name: misp_mail
    image: namshi/smtp  

  redis:
    container_name: misp_redis    
    image: redis:5.0
    restart: unless-stopped    

  db:
    container_name: misp_db
    image: mysql:5.7
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password    
    hostname: ${MYSQL_HOST}
    volumes:
      - ${DATA_DIR}/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  modules:
    container_name: misp_modules
    image: coolacid/misp:modules-latest
    environment:
      - "REDIS_BACKEND=redis"
    depends_on:
      - redis
      - db

  core:
    depends_on:
      - db
      - redis
      - mail
      - modules
    container_name: misp_core
    image: marcelosz/misp:core-latest
    restart: unless-stopped
    volumes:
      - /dev/urandom:/dev/random
      - ${DATA_DIR}/core/web:/var/www/MISP
    ports:
      - 80:80
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_MISP_USER=${MYSQL_USER}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_MISP_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MISP_ADMIN_EMAIL=${MISP_ADMIN_EMAIL}
      - MISP_ADMIN_PASSPHRASE=${MISP_ADMIN_PASSPHRASE}
      - MISP_BASEURL=${MISP_BASEURL}
      - POSTFIX_RELAY_HOST=${POSTFIX_RELAY_HOST}
      - TIMEZONE=${TIMEZONE}
